### ISSUE TITLE
Could you please add a License ?

### ISSUE THREAD

**Issue by M0dM** [dgerosa/processify#1]
Hi @dgerosa 

I am very interested in this repository and not in other tools inside your skywalker library.
As this repo does not have a license, it avoids me to use it.

Could you please add a license file to the repo ?

Thanks for all the great work!

M0dM

**Comment by dgerosa** [comment]
Hi,

I've added a MIT licence. 
@schlamar : I've developed this code from one of your gists, please let me know if you disagree with it having a MIT licence.

Davide

**Comment by M0dM** [comment]
Thanks ;)
